### ISSUE TITLE
There will be an error running the client.mutateRow()

### ISSUE THREAD

**Issue by hyqlmy** [626626cdllp/infrastructure#1]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/dist-packages/hbase/Hbase.py", line 1250, in mutateRow
    self.send_mutateRow(tableName, row, mutations)
  File "/usr/local/lib/python3.6/dist-packages/hbase/Hbase.py", line 1254, in send_mutateRow
    self._oprot.writeMessageBegin('mutateRow', TMessageType.CALL, self._seqid)
  File "/usr/local/lib/python3.6/dist-packages/thrift/protocol/TBinaryProtocol.py", line 54, in writeMessageBegin
    self.writeI32(TBinaryProtocol.VERSION_1 | type)
  File "/usr/local/lib/python3.6/dist-packages/thrift/protocol/TBinaryProtocol.py", line 119, in writeI32
    self.trans.write(buff)
  File "/usr/local/lib/python3.6/dist-packages/thrift/transport/TSocket.py", line 161, in write
    raise TTransportException(message="unexpected exception", inner=e)
thrift.transport.TTransport.TTransportException: unexpected exception

**Comment by hyqlmy** [comment]
It's OK
